### PR TITLE
Reduced HTTP dependency requirement

### PR DESCRIPTION
**Pull request by Shamsudeen12**
## Status

**READY*

## Description

Reduced the minimum requirement for the HTTP package from 1.1.0 to 0.13.4 to improve compatibility with other packages

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by Shamsudeen12** [comment]
Hi @manuelperez96 Can you please review and make a new version for this change?

**Comment by manuelperez96** [comment]
I have a lot of work now. I try upload the changes as soon as possible

**Comment by Shamsudeen12** [comment]
> I have a lot of work now. I try upload the changes as soon as possible

Okay. Thank you 🙏

**Comment by manuelperez96** [comment]
HI, thanks for the update. I already upload the new version to pudev. I included in the readme as a contributor.

**Pull request merged**
